#ifndef YEALINK_API_ADAPTED_PEER_CONNECTION_INTERFACE_H_
#define YEALINK_API_ADAPTED_PEER_CONNECTION_INTERFACE_H_

namespace yealink {


}  // namespace yealink

#endif  // YEALINK_API_ADAPTED_PEER_CONNECTION_INTERFACE_H_
